name: reviewdog
on: [pull_request]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          golangci_lint_flags: "--config=.golangci.yaml"
          filter_mode: diff_context
          reporter: github-pr-review
          fail_level: error

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - uses: reviewdog/action-actionlint@e58ee9d111489c31395fbe4857b0be6e7635dbda # v1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
          fail_level: error

  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v4
      - uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 # v1
        with:
          reporter: github-pr-review
          level: warning
          filter_mode: diff_context
          fail_level: error
